language: go

dist: trusty
sudo: required

go:
- 1.9
- "1.10"
- tip

env:
  - DEP_VERSION=0.4.1 HUGO_VERSION=0.42.1 GORELEASER_VERSION=0.77.1 NFPM_VERSION=0.9.1

cache: apt

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - wget https://github.com/goreleaser/goreleaser/releases/download/v${GORELEASER_VERSION}/goreleaser_amd64.deb
  - sudo dpkg -i goreleaser_amd64.deb
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
  - wget https://github.com/goreleaser/nfpm/releases/download/v${NFPM_VERSION}/nfpm_amd64.deb
  - sudo dpkg -i nfpm_amd64.deb
addons:
  apt:
    update: true
    packages:
    - rpm

jobs:
  include:
  - stage: test
    if: type = pr
    script: |
      dep ensure -v -vendor-only
      go test -race .
  - stage: goreleaser
    if: type = push
    script: |
      dep ensure -v -vendor-only
      cd cmd/cs
      dep ensure -v -vendor-only
      cd ../exo
      dep ensure -v -vendor-only
      cd ../..
      go run cmd/exo/completion/main.go
      goreleaser --snapshot --skip-sign
  - stage: gh-pages
    if: branch = master AND type = push
    script: |
      dep ensure -v -vendor-only
      go test -coverprofile=coverage.out -covermode=atomic .
      npm i codeclimate-test-reporter
      npx codeclimate-test-reporter < coverage.out
      cd website
      sh prepare.sh
      hugo
      cd public
      git init
      git config user.name "TravisCI"
      git config user.email "travis@travis-ci.org"
      git add .
      git commit -m "Deployed to github pages"
      git push -f -q "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" master:gh-pages
