language: go

go:
  - "1.13.x"
  - "1.14.x"
  - tip

cache: apt

env:
  - HUGO_VERSION=0.58.3 GOLANGCI_LINT_VERSION=1.25.0

script:
  - '[ "$(echo "$TRAVIS_GO_VERSION" | perl -pe "s/\\.[x\\d]+$//")" = "1.10" ] && go test -v ./... || go test -mod vendor -v ./...'
  - '[ "$(echo "$TRAVIS_GO_VERSION" | perl -pe "s/\\.[x\\d]+$//")" = "1.10" ] && go install || go build -mod=vendor'

jobs:
  include:
    - stage: golangci-lint
      go: "1.13.x"
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}
        - GO111MODULE=off golangci-lint run ./...
        - go test -v -mod=vendor ./...
        - go build -mod=vendor
    - stage: gh-pages
      go: "1.13.x"
      if: branch = master AND type = push
      script: |
        cd website
        sh prepare.sh
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
        sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
        hugo
        cd public
        git init
        git config user.name "TravisCI"
        git config user.email "travis@travis-ci.org"
        git add .
        git commit -m "Deployed to GitHub pages"
        git push -f -q "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" master:gh-pages
