language: go

go:
  - "1.10.x"
  - "1.11.x"

cache: apt

addons:
  apt:
    update: true
    packages:
      - rpm

env:
  - GO111MODULE=on HUGO_VERSION=0.49.2 GOLANGCI_LINT_VERSION=1.10.2

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}

jobs:
  include:
    - go: "1.10.x"
      script:
        - golangci-lint run ./...
        - go test -v ./...
        - go build
    - go: "1.11.x"
      script:
        - go test -v -mod=vendor ./...
        - go build -mod=vendor
    - stage: goreleaser
      go: "1.11.x"
      script:
        - curl -sL https://git.io/goreleaser | head -n -2 | bash
        - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin
        - goreleaser --snapshot --skip-sign
    - stage: gh-pages
      go: "1.11.x"
      if: branch = master AND type = push
      script: |
        cd website
        sh prepare.sh
        wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
        sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
        hugo
        cd public
        git init
        git config user.name "TravisCI"
        git config user.email "travis@travis-ci.org"
        git add .
        git commit -m "Deployed to GitHub pages"
        git push -f -q "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" master:gh-pages
