ignored = ["github.com/exoscale/egoscale"]

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/alecthomas/chroma"
  version = "0.4.0"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "1.33.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
